### ISSUE TITLE
UI - using same function for new entry and edit entry

### ISSUE THREAD

**Issue by sterresteeg** [Deverence/blueprinting#10]
**Is your feature request related to a problem? Please describe.**
I am making a datatable and try to combine the "edit" and "create" functionality by opening the same modal for both options. This was possible in previous blueprints. However, to make the modal prefilled for the edit option, you have to add an object out-pin to the function. When you do that the triggers both get updated with an object in-pin.
I noticed that this empty in-pin causes the effect that the event trigger for this button does not work anymore. I tested this with a dummy function without object in-pin and then the event gets triggered without problem.

**Describe the solution you'd like**
I would like to use the same function for edit and create options.

**Describe alternatives you've considered**
Making two separate functions that are completely identical except for the prefilled option, and of course the ID of the form.
But then I also have to change my save function to select the appriopriate form variable.

![image](https://user-images.githubusercontent.com/36989178/48643369-d2e4f800-e9df-11e8-9eb2-f817c43b6fa4.png)

**Comment by jessereitsma** [comment]
Do you have a link to the Blueprint? 
Wondering if you create the row pin yourself or if it was auto created (Mabye it doesn’t even matter in this case)

**Comment by sterresteeg** [comment]
- there was no blueprint, since I worked around it by making two functions as described in the issue
- the datatable did not work anymore on gps.deverence.com so I could not change it back
- copied the blueprint to suzanne-bp.deverence.com and there it does work without problem
- trigger still has the auto-created Row in-pin, but the button works so I'm fine with it
