### ISSUE TITLE
Disable Cache sidebar

### ISSUE THREAD

**Issue by Llamarvin** [Deverence/blueprinting#11]
**Describe the bug**

**To Reproduce**
1. Go to 'any BP'
2. Click on 'rightclick on a folder and add a BP'

**Expected behavior**
if you add an BP or move one, i expect it to add it live

**Additional context**
a Disable Cache would solve this problem

**Comment by jessereitsma** [comment]
Issue relates to https://github.com/Deverence/core/issues/5737

**Comment by jessereitsma** [comment]
This issue has been resolved and will work after the next deploy
