### ISSUE TITLE
UI - improve block dynamic content

### ISSUE THREAD

**Issue by sterresteeg** [Deverence/blueprinting#13]
**Is your feature request related to a problem? Please describe.**
It was not immediately clear what was expected on the "content" pin of the dynamic content.
I expected I had to make a variable, and return the value of this variable in a function.
But the "content" pin can be used to add a default value for the content.

**Describe the solution you'd like**
change "content" to "default content"
add an information text: "default content can be replaced using update dynamic content in a function"

**Describe alternatives you've considered**
Once you know it, you will probably not forget, but for new or infrequent users this would be better.

**Additional context**

![image](https://user-images.githubusercontent.com/36989178/49101505-a1d5b480-f276-11e8-9115-104ec466ffb2.png)

**Comment by dhenkes** [comment]
Added a tooltip to the action and to the content in pin explaining what everything does.
